LTTS-ADAS/ltts_adas

cvat-ui/src/components/annotation-page/standard-workspace/standard-workspace.tsx, cvat-ui/src/components/annotation-page/top-bar/right-group.tsx, cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/components/header/header.tsx, cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
=> role based dropdown in annotation

cvat-ui/src/components/annotation-page/top-bar/right-group.tsx
=> Role based page raju develop

cvat/apps/engine/backup.py
=> Project id sk develop

cvat/apps/engine/templates/email_template.py, cvat/apps/engine/views.py
=> Job email notification sk develop

cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/resize-control.tsx
=> rectify zoomout issue

cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx, cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx
=> removed layerslider,datasetrepository field,defaultchunk size 1

cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/resize-control.tsx, cvat-ui/src/components/annotation-page/top-bar/right-group.tsx, cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
=> Single delete popup raju dev

cvat-ui/src/components/header/header.tsx, cvat-ui/src/components/project-page/project-page.tsx, cvat-ui/src/components/task-page/details.tsx, cvat-ui/src/components/task-page/top-bar.tsx, cvat-ui/src/components/tasks-page/task-item.tsx, cvat-ui/src/components/tasks-page/tasks-page.tsx, cvat-ui/src/components/tasks-page/top-bar.tsx, cvat-ui/src/containers/tasks-page/task-item.tsx, cvat-ui/src/containers/tasks-page/tasks-list.tsx
=> Action button raj dev

cvat-ui/src/components/task-page/task-page.tsx, cvat-ui/src/components/task-page/top-bar.tsx
=> action link hide in task tob bar for normal user

cvat-ui/src/actions/auth-saga-actions.ts, cvat-ui/src/components/email-confirmation-page/email-confirmed.tsx, cvat-ui/src/components/register-page/register-form.tsx, cvat-ui/src/components/task-page/job-list.tsx, cvat-ui/src/components/task-page/user-selector.tsx, cvat-ui/src/containers/register-page/register-page.tsx, cvat-ui/src/sagas/auth-saga.ts
=> Creataccount raj dev

cvat/apps/authentication/urls.py, cvat/apps/authentication/views.py, cvat/apps/engine/views.py, cvat/settings/base.py, cvat/settings/development.py
=> email notification on verification

cvat-core/src/user.js
=> auto login with email verifiction

cvat-core/src/server-proxy.js
=> added user friendly message for 504 and wrong credential

cvat-core/src/server-proxy.js
=> add ternary operator

cvat-ui/src/components/annotation-page/top-bar/right-group.tsx, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/email-confirmation-page/email-confirmed.tsx
=> Email confirmations raj dev

cvat/apps/engine/views.py
=> Verify email sk develop

cvat-core/src/user.js, cvat-ui/src/actions/useragreements-actions.ts, cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/task-page/job-list.tsx, cvat-ui/src/components/useragreements-acceptance-page/NDA-acceptance-form.tsx
=> Frames raj dev

cvat-ui/src/components/cvat-app.tsx
=> enbled email confirmation page

cvat/apps/engine/backup.py
=> project_id changes

cvat/apps/authentication/auth_basic.py, cvat/apps/engine/views.py, cvat/apps/restrictions/models.py, cvat/apps/restrictions/serializers.py, cvat/apps/restrictions/views.py
=> Bug fix sk develop

cvat-core/src/api-implementation.js, cvat-core/src/api.js, cvat-core/src/server-proxy.js, cvat-ui/src/actions/acceptance-saga-action.ts, cvat-ui/src/components/annotation-page/top-bar/annotation-menu.tsx, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/useragreements-acceptance-page/NDA-acceptance-form.tsx, cvat-ui/src/containers/annotation-page/top-bar/annotation-menu.tsx
=> accpetance submited

cvat-core/src/server-proxy.js, cvat-ui/src/actions/acceptance-saga-action.ts, cvat-ui/src/components/annotation-page/top-bar/annotation-menu.tsx, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/notifications-reducer.ts, cvat-ui/src/sagas/acceptance-saga.ts, cvat-ui/src/sagas/index.ts
=> Nda raj dev

cvat/apps/restrictions/models.py, cvat/apps/restrictions/views.py
=> Acceptance dk develop

cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/sagas/acceptance-saga.ts
=> bug fixed acceptance redirect issues

cvat-ui/src/components/annotation-page/top-bar/annotation-menu.tsx
=> Bugfixedaccept raj dev

cvat/apps/authentication/auth_basic.py, cvat/apps/restrictions/models.py
=> bug fixed for duplicate entry nda

cvat/apps/authentication/auth_basic.py
=> basic_auth

cvat-ui/src/components/annotation-page/top-bar/left-group.tsx, cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/reducers/settings-reducer.ts
=> autosave enabled in frontend side

cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx, cvat-ui/src/components/create-task-page/create-task-content.tsx, cvat-ui/src/components/file-manager/file-manager.tsx, cvat-ui/src/containers/file-manager/file-manager.tsx
=> segment size can be max file no

cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx, cvat-ui/src/components/file-manager/file-manager.tsx
=> changed segment size field error message

cvat-ui/src/components/annotation-page/top-bar/left-group.tsx, cvat-ui/src/components/email-confirmation-page/email-confirmed.tsx, cvat-ui/src/components/useragreements-acceptance-page/NDA-acceptance-form.tsx
=> Pdf raj dev

cvat-ui/src/components/task-page/details.tsx, cvat-ui/src/components/task-page/job-list.tsx, cvat-ui/src/containers/task-page/details.tsx
=> Assigneehide raj dev

cvat-ui/src/components/annotation-page/top-bar/left-group.tsx, cvat-ui/src/components/annotation-page/top-bar/right-group.tsx
=> Delete raj dev

cvat-ui/src/components/task-page/job-list.tsx, cvat-ui/src/components/task-page/user-selector.tsx
=> Jobstatus raj dev

cvat/apps/engine/urls.py, cvat/apps/engine/views.py
=> removing prnt stamnts

cvat/apps/engine/views.py
=> Search sk develop
